### PR TITLE
Fix "Enable notification emails"

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by artonge** [comment]
Should get fixed by this one too: https://github.com/nextcloud/activity/pull/589

**Review by artonge — APPROVED** [review]

**Comment by artonge** [comment]
But backport is nice

**Comment by NextClaus** [comment]
When do you fix this annoying bug?
- Notification checkbox cannot be enabled again in GUI (but only on database level)
- Notification mails (if there are file changes in a folder) don't get sent

**Comment by nickvergessen** [comment]
Feel free to send a Pull request and I will test and merge it by the end of the day

**Comment by NextClaus** [comment]
A "Pull request" seems to be a kind of suggestion for a code change. I'm not a coder at all. So I cannot contribute anything than telling you that the change which was implemented here in #609 doesn't seem to work. But "sandro-tassa" added a comment on 12 Oct. Maybe this helps fixing it?

**Pull request merged**
