### PR TITLE
Create an unordered list for the list of activities

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Fixes https://github.com/nextcloud/activity/issues/1020

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| Screenshot from 2023-01-31 11-18-14 | Screenshot from 2023-01-31 14-41-45

### CODE REVIEW

**Comment by nickvergessen** [comment]
~~That's only half of it.~~

Files sidebar already uses ul-li:
https://github.com/nextcloud/activity/blob/master/src/views/ActivityTab.vue#L32-L37

**Comment by JuliaKirschenheuter** [comment]
Hi @michaelnissenbaum,

From the last review you mentioned that the content of activities should be a list and not just mixed content. I'm curious if i achieved it. In current case i have a complex content inside, not only some text (please see the screenshots above). Thank you!

**Comment by JuliaKirschenheuter** [comment]
> ~That's only half of it.~

Ok, does it mean i should replace it on other places (please write me which ones)? *besides sidebar

**Comment by nickvergessen** [comment]
> Ok, does it mean i should replace it on other places (please write me which ones)? *besides sidebar

Sidebar is already fixed, and those are the 2 places

**Review by Pytal — APPROVED** [review]

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter the new code looks good to me.

**Pull request merged**
