### PR TITLE
Reduce the number of 4000chars columns

### PR DESCRIPTION
**Pull request by nickvergessen**
Since we don't have oracle users, we should merge this asap.
Downstream: https://github.com/owncloud/activity/pull/512/files

@LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Any metrics on migration duration?

**Comment by nickvergessen** [comment]
I tested our instance, 30 MB activity table with 60k entries too about ~2 seconds.

```
2016-10-18T09:10:21+00:00 Updating <activity> ...
2016-10-18T09:10:23+00:00 Updated <activity> to 2.4.1
```

**Comment by nickvergessen** [comment]
Okay to merge? @MorrisJobke

**Comment by MorrisJobke** [comment]
Tested and works 👍

**Pull request merged**
