### PR TITLE
Fix monochrome icon detection for correct dark mode invert

### PR DESCRIPTION
**Pull request by nickvergessen**
Before | After
---|---
Bildschirmfoto von 2021-07-02 09-39-34 | Bildschirmfoto von 2021-07-02 09-39-20

### CODE REVIEW

**Comment by nickvergessen** [comment]
@juliushaertl when did you start to use those icons?

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Right from the beginning of the activity app integration 

https://github.com/nextcloud/deck/pull/607
https://github.com/nextcloud/deck/commit/18f92f7b54f89db530272afcf540ac12db20b8e6#diff-71e6f764bb054f7d7d0ad86deedd2006c5ba615454bd81eda5e79e0e300f574aR68

**Pull request merged**
