### PR TITLE
[stable12] Ignore paths from chunking

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

Backport #156

### CODE REVIEW

**Comment by MorrisJobke** [comment]
umm this is not in the daily-stable12 ... and this is somehow against master ... what happened here? https://github.com/nextcloud/activity/blob/stable12/lib/FilesHooks.php#L141

**Comment by danger89** [comment]
This issue is not fixed in 12.0.3rc2.

**Comment by major5012** [comment]
This issue is not fixed in 12.0.4 which was installed on 1/4/2018.

Level | App | Message | Time
-- | -- | -- | --
Error | PHP | Undefined offset: 3 at /mypathhere/apps/activity/lib/FilesHooks.php#620 | 2018-01-16T12:59:50-0700

**Comment by nickvergessen** [comment]
That's a different error which is fixed with https://github.com/nextcloud/activity/pull/229 and therefor will come in 12.0.5

**Pull request merged**
