### PR TITLE
Remove horizontal scrolling for activity view

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Resolves https://github.com/nextcloud/activity/issues/1480

### 🖼️ Screenshots

|  Before   | After                                                        |
|-------------|---------------------------------------------------------------|
| Screenshot from 2023-12-28 10-49-45 | Screenshot from 2023-12-28 10-49-34

### CODE REVIEW

**Review by artonge — COMMENTED** [review]
Doesn't this solution crops the content of the activity if it overflows?

**Review by artonge — APPROVED** [review]

**Review by emoral435 — APPROVED** [review]

**Review by emoral435 — CHANGES_REQUESTED** [review]
image

Check the console, it seems like some of the changes have affected how some of the components render :(

**Comment by JuliaKirschenheuter** [comment]
> Check the console, it seems like some of the changes have affected how some of the components render :(

All i've changed for this PR were 2 lines of css. This is a problem, but not related to PR

**Review by emoral435 — APPROVED** [review]
Sorry for the confusion on my end, LGTM!

**Pull request merged**
