### PR TITLE
Don't add empty entries to the objects array

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Will this be backported? It is quite a problem on Android if no activities at all are shown.

**Comment by nickvergessen** [comment]
Backport doesnt help as releases just went out and it would be broken 4-6 more weeks.

**Comment by tobiasKaminsky** [comment]
Then I'll add a fix to Android :+1:

**Pull request merged**
