### PR TITLE
Make avatars smaller to fit inline [nextcloud/server#2012]

### PR DESCRIPTION
**Pull request by eppfel**
As discussed in nextcloud/server#2012

### CODE REVIEW

**Comment by eppfel** [comment]
@nextcloud/designers Can someone review this?

**Comment by MorrisJobke** [comment]
👍

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
yet another avatar size to be cached 🙈 
👍

**Comment by eppfel** [comment]
@nickvergessen We just try to get a hold of this in nextcloud/server#2012 . Hopefully there will be only three sizes left: 21px, 32px and 128px. If you know of others, please add them.

**Comment by nickvergessen** [comment]
Avatars are one pixel too far down now:
bildschirmfoto vom 2016-11-07 12-09-58

Will fix in a second PR

**Pull request merged**
