### PR TITLE
[stable28] bump ncvue to v8.6.2

### PR DESCRIPTION
**Pull request by JuliaKirschenheuter**
Bump NcVue to `v8.6.2`

### CODE REVIEW

**Review by susnux — APPROVED** [review]
Good, but update master as well as otherwise stable branches are ahead  of main branches

**Review by Pytal — APPROVED** [review]

**Comment by Pytal** [comment]
An admin might have to update required status checks

**Comment by JuliaKirschenheuter** [comment]
closing branch because name should not start with "stable28"

**Pull request closed without merging**
