### PR TITLE
Apiv2

### LINKED ISSUE #104: Clarify v2 endpoint
Can you please clarify the differences between v1 and v2 endpoints (docs for v1 doesn't seem to exist), and in which version did this change?

### PR DESCRIPTION
**Pull request by nickvergessen**
- [x] Requires https://github.com/nextcloud/server/pull/3977
- [x] Make routes work
- [x] Use new routes
- [x] Kill old endpoint + routes
- [x] Make sure the endpoint only returns documented/necessary things
- [x] ETag support
- [x] Capability

Fix #104

### CODE REVIEW

**Comment by mario** [comment]
Currently fetching activities needs an admin user. I think that is a bug, so please fix - thanks!

**Comment by nickvergessen** [comment]
@mario fixed

**Comment by nickvergessen** [comment]
@mario added capabilities and ETag support. Want to test it again?

**Comment by nickvergessen** [comment]
@rullzer can you help testing? Just checkout the branch and browse the normal activity app and sidebar a bit, thanks

**Pull request merged**
