### PR TITLE
Fix for NC Issue 18695

### PR DESCRIPTION
**Pull request by Dennis1993**
We can fix this issue/idea by bring in a simple line. If we move the timestamp a litte bit more to the top then we have a problem with long entries which make the timestamp not readable.

Thats my idea

image

https://github.com/nextcloud/server/issues/18695

### CODE REVIEW

**Comment by nickvergessen** [comment]
I think instead we should adjust the position of the timestamp

**Comment by artonge** [comment]
Not necessary anymore as of the vue rewrite from a few month ago.

**Comment by artonge** [comment]
hello@josandcamila.com

**Comment by artonge** [comment]
Not necessary anymore as of the vue rewrite of a few month ago.

**Pull request closed without merging**
