### PR TITLE
fix: chunk delete in query

### PR DESCRIPTION
**Pull request by miaulalala**

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by come-nc — APPROVED** [review]

**Review by nickvergessen — APPROVED** [review]

**Comment by miaulalala** [comment]
Cherry-picks fail too:

```
git cherry-pick 9bee2e2
fatal: bad revision '9bee2e2'

git cherry-pick 9bee2e2bf373b407ea2e5887f7aac4a5e8a58862
fatal: bad object 9bee2e2bf373b407ea2e5887f7aac4a5e8a58862
```

Any tips @nickvergessen @ChristophWurst ?

**Comment by nickvergessen** [comment]
```
git fetch origin master
```
?

**Pull request merged**
