### PR TITLE
 Display the home icon for empty paths (root folder) 

### LINKED ISSUE #210: Moving file to root folder doesn’t show anything as »moved to« location
If you move a file from somewhere to the root folder, Activity shows nothing as the target location:
screenshot from 2017-10-09 21-08-18

Instead, we should show the `icon-home`, linked to the Home folder.

### PR DESCRIPTION
**Pull request by nickvergessen**
> bildschirmfoto vom 2017-10-10 12-23-22

Fix #210

### CODE REVIEW

**Comment by jancborchardt** [comment]
Can you also add a title attribute saying "Home"? Looks good otherwise!

**Comment by nickvergessen** [comment]
Done

**Comment by MorrisJobke** [comment]
@nickvergessen What is the status of the backport?

**Comment by nickvergessen** [comment]
Not too important, will do for 12.0.6

**Pull request merged**
