### PR TITLE
[stable27] perf(dashboard): implement widget item api v2

### PR DESCRIPTION
**Pull request by st3iny**
Manual backport of #1284 

Tested locally and works.

### CODE REVIEW

**Review by come-nc — APPROVED** [review]

**Comment by blizzz** [comment]
@st3iny some CI is read including static analysis. Please check.

**Comment by st3iny** [comment]
The **phpunit** job fails with a transient error during `composer install` (not able to unzip a zip file). I restarted all failed jobs.

---

The **static analysis** job fails here but works locally. My guess is that is not using the most recent version of `nextcloud/ocp` that contains the right interfaces. The interface `IReloadableWidget` clearly exists on server master and stable27.

Running `composer install && composer run psalm` reports no errors locally.

https://github.com/nextcloud/server/blob/master/lib/public/Dashboard/IReloadableWidget.php
https://github.com/nextcloud/server/blob/stable27/lib/public/Dashboard/IReloadableWidget.php

**Comment by ChristophWurst** [comment]
CI should be fixed :crossed_fingers:

**Comment by ChristophWurst** [comment]
It passes

**Comment by ChristophWurst** [comment]
@artonge @miaulalala maintainer approval? then :shipit: 

RC blocking is to be bypassed because this change is planned for 27.1.0

**Review by AndyScherzinger — APPROVED** [review]

**Pull request merged**
