### PR TITLE
Start the contacts popup

### PR DESCRIPTION
**Pull request by nickvergessen**
@georgehrke can you help? the popup is always in the top left corner of the activity stream...

- [x] Position
- [x] Sidebar

### CODE REVIEW

**Comment by georgehrke** [comment]
@nickvergessen What do you mean with sidebar?

**Comment by nickvergessen** [comment]
Activities in the sidebar of the file list didnt have it.
Fixed it with my last commit. Thanks for the help.

Ready to go?

**Comment by georgehrke** [comment]
lgtm

**Comment by jancborchardt** [comment]
@georgehrke I now added checkboxes to the server issue at https://github.com/nextcloud/server/issues/4532 so you can check off when an app is fixed :)

**Pull request merged**
