### PR TITLE
Fix mail table columns to match the activity table

### LINKED ISSUE #503: amq_subjectparams has a different size than subjectparams
The subjectparams table of oc_activity_mq has a size limit of 4000 characters while the subjectparams of oc_activity are a longtext column. 

@nickvergessen Is there any reasoning behind that? Wouldn't it make sense to have a longtext for the mq table as well, since otherwise activity entries might not be added to the mq table if the subject params json exceeds 4000 chars.

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #503

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Tests not happy with the app id shortening

**Comment by nickvergessen** [comment]
the string was 33 chars...

**Pull request merged**
