### PR TITLE
getUsersFavoritingObject is moved to the manager

### LINKED ISSUE #499: Call to a member function getUsersFavoritingObject() on null
### Steps to reproduce
1. Create a public share link for a folder
2. Select "Allow upload and editing"
3. Open share in private windows
4. Delete a file

### Expected behaviour

Delete the file

### Actual behaviour

Error deleting file "xzy".

```
{"reqId":"X7IEDmn0VvhEEs5hBSOq","level":1,"time":"2020-09-21T18:33:31+00:00","remoteAddr":"192.168.10.1","user":"--","app":"no app in context","method":"DELETE","url":"/public.php/webdav/Test.md","message":"Deprecated event type for {\"[object] (OCP\\SabrePluginEvent)\":{\"*statusCode\":200,\"*message\":\"\",\"*server\":{\"[object] (OCA\\DAV\\Connector\\Sabre\\Server)\":{\"tree\":\"[object] (OCA\\DAV\\Connector\\Sabre\\ObjectTree)\",\"*baseUri\":\"/public.php/webdav/\",\"httpResponse\":\"[object] (Sabre\\HTTP\\Response)\",\"httpRequest\":\"[object] (Sabre\\HTTP\\Request)\",\"sapi\":\"[object] (Sabre\\HTTP\\Sapi)\",\"*plugins\":[],\"transactionType\":null,\"protectedProperties\":{\"...\":\"Over 20 items, aborting normalization\"},\"debugExceptions\":false,\"resourceTypeMapping\":[],\"enablePropfindDepthInfinity\":true,\"xml\":\"[object] (Sabre\\DAV\\Xml\\Service)\",\"*listeners\":{\"...\":\"Over 20 items, aborting normalization\"},\"*wildcardListeners\":[],\"*listenerIndex\":[],\"*logger\":null}},\"Symfony\\Contracts\\EventDispatcher\\EventpropagationStopped\":false}}: null","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36","version":"21.0.0.0"}
{"reqId":"X7IEDmn0VvhEEs5hBSOq","level":4,"time":"2020-09-21T18:33:31+00:00","remoteAddr":"192.168.10.1","user":"--","app":"webdav","method":"DELETE","url":"/public.php/webdav/Test.md","message":{"Exception":"Error","Message":"Call to a member function getUsersFavoritingObject() on null","Code":0,"Trace":[{"file":"/home/vagrant/code/nextcloud/apps/activity/lib/FilesHooks.php","line":242,"function":"getFileChangeActivitySettings","class":"OCA\\Activity\\FilesHooks","type":"->","args":[1793,["admin"]]},{"file":"/home/vagrant/code/nextcloud/apps/activity/lib/FilesHooks.php","line":177,"function":"addNotificationsForFileAction","class":"OCA\\Activity\\FilesHooks","type":"->","args":["/AAAAAAA/Test.md","file_deleted","deleted_self","deleted_by"]},{"file":"/home/vagrant/code/nextcloud/apps/activity/lib/FilesHooksStatic.php","line":63,"function":"fileDelete","class":"OCA\\Activity\\FilesHooks","type":"->","args":["/AAAAAAA/Test.md"]},{"file":"/home/vagrant/code/nextcloud/lib/private/legacy/OC_Hook.php","line":110,"function":"fileDelete","class":"OCA\\Activity\\FilesHooksStatic","type":"::","args":[{"run":true,"path":"/AAAAAAA/Test.md"}]},{"file":"/home/vagrant/code/nextcloud/lib/private/Files/View.php","line":1274,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","delete",{"run":true,"path":"/AAAAAAA/Test.md"}]},{"file":"/home/vagrant/code/nextcloud/lib/private/Files/View.php","line":1144,"function":"runHooks","class":"OC\\Files\\View","type":"->","args":[["delete"],"/AAAAAAA/Test.md"]},{"file":"/home/vagrant/code/nextcloud/lib/private/Files/View.php","line":718,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["unlink","/Test.md",["delete"]]},{"file":"/home/vagrant/code/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":466,"function":"unlink","class":"OC\\Files\\View","type":"->","args":["/Test.md"]},{"file":"/home/vagrant/code/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":183,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[]},{"file":"/home/vagrant/code/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":295,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->","args":["Test.md"]},{"file":"/home/vagrant/code/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/home/vagrant/code/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:DELETE",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/home/vagrant/code/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/home/vagrant/code/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/home/vagrant/code/nextcloud/apps/dav/appinfo/v1/publicwebdav.php","line":113,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/home/vagrant/code/nextcloud/public.php","line":81,"args":["/home/vagrant/code/nextcloud/apps/dav/appinfo/v1/publicwebdav.php"],"function":"require_once"}],"File":"/home/vagrant/code/nextcloud/apps/activity/lib/FilesHooks.php","Line":193,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36","version":"21.0.0.0"}
```

image

### Server configuration

**PHP version: 7.4**

**Nextcloud version: master** (see Nextcloud admin page)

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix #499 

- [x] Requires: https://github.com/nextcloud/server/pull/23184
Ref https://sentry.io/organizations/nextcloud-gmbh/issues/1927876255

### CODE REVIEW

**Review by MorrisJobke — APPROVED** [review]
Makes sense 👍

**Review by icewind1991 — APPROVED** [review]

**Review by ChristophWurst — APPROVED** [review]
Though I would say if you expect the `TagManager` then have that injected in the constructor

**Comment by nickvergessen** [comment]
Well let's just add it to the interface once the situation cleared up and we know it's working.

**Pull request merged**
