### PR TITLE
[stable23] groupfolders+acl

### PR DESCRIPTION
**Pull request by ArtificialOwl**
backport of #992

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by PVince81** [comment]
@icewind1991 second review ?

**Comment by blizzz** [comment]
Still needed?

**Review by icewind1991 — APPROVED** [review]

**Comment by PVince81** [comment]
@ArtificialOwl can you fix DCO ? maybe rebase then to get a fresh CI run

**Comment by blizzz** [comment]
@ArtificialOwl Cypress is unrelated?

**Comment by artonge** [comment]
Cypress tests are unrelated.

**Pull request merged**
