### PR TITLE
Don't throw when we are deleting nothing

### PR DESCRIPTION
**Pull request by nickvergessen**
Fix nextcloud/server#2688

Ref https://github.com/nextcloud/server/issues/2600#issuecomment-266201198

### CODE REVIEW

**Comment by LukasReschke** [comment]
We should probably backport this, right?

**Comment by nickvergessen** [comment]
Yes, backport is in #95

**Comment by tflidd** [comment]
backport for NC 10 as well? https://help.nextcloud.com/t/email-notification-does-not-work-error-in-logging-file/6928

**Comment by nickvergessen** [comment]
Right, we backported the previous change: https://github.com/nextcloud/activity/pull/54
So yes need to backport this to 10 as well

**Comment by nickvergessen** [comment]
Done in #99

**Comment by JSoko** [comment]
It seems that this fix isn't included in 11.0.1 RC1

**Comment by tx7** [comment]
I'm using external storage without encryption, and I still having this errors.
This error didn't exist in NC10.

`imagecreatefromstring(): Empty string or invalid image at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/lib/private/legacy/image.php#597

fclose() expects parameter 1 to be resource, boolean given at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/lib/private/Files/Storage/Local.php#218

fread() expects parameter 1 to be resource, boolean given at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/lib/private/Files/Storage/Local.php#217

fopen(/media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/data/tien/files/media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/core/img/filetypes/audio.svg): failed to open stream: No such file or directory at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/lib/private/Files/Storage/Local.php#216

filesize(): stat failed for /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/data/tien/files/media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/core/img/filetypes/audio.svg at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/lib/private/Files/Storage/Local.php#211

fopen(/media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/data/tien/files/media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/core/img/filetypes/audio.svg): failed to open stream: No such file or directory at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/lib/private/Files/Storage/Local.php#216


 filesize(): stat failed for /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/data/tien/files/media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/core/img/filetypes/audio.svg at /media/54bf67db-da31-4c50-bb3c-27140944b223/www/nextcloud/lib/private/Files/Storage/Local.php#211`

**Comment by nickvergessen** [comment]
Yeah, I merged it on the day after. But Should be included in RC2 (when we do one) or the final.

**Comment by tx7** [comment]
Looking forward to it.
Thanks for the info.

**Pull request merged**
