### PR TITLE
Use button element and add label to make copy RSS link button accessible

### PR DESCRIPTION
**Pull request by Pytal**
Before | After
--- | ---
image | image

### CODE REVIEW

**Review by artonge — APPROVED** [review]

**Review by skjnldsv — APPROVED** [review]

**Review by JuliaKirschenheuter — APPROVED** [review]

**Comment by nickvergessen** [comment]
CI could be green after https://github.com/nextcloud/activity/pull/1129 but should rebased once that is in to be sure.

**Comment by nickvergessen** [comment]
Rebased for green CI

**Pull request merged**
