### PR TITLE
Use the language of the user when sending emails

### PR DESCRIPTION
**Pull request by nickvergessen**
Before all emails are english, with this they are translated again.

- [x] Requires https://github.com/nextcloud/server/pull/2432

@LukasReschke @MorrisJobke

### CODE REVIEW

**Comment by MorrisJobke** [comment]
For me the message is only partially translated:

```
Hello admin,

You are receiving this email because the following things happened at http:\/\/localhost\/

* You created sdf - Heute um 13:12:04

```

But the relative date works - the relative date is created here: https://github.com/nextcloud/activity/pull/84/files#diff-f62c701dd29645a0fe35af8852cfa9ccR255

**Comment by nickvergessen** [comment]
This PR only fixes the "You created sdf" section :-O

**Comment by MorrisJobke** [comment]
Restarted CI, because server PR was merged

**Comment by MorrisJobke** [comment]
:+1:

**Pull request merged**
