### PR TITLE
Harden code to not explode if a storage has no owner

### PR DESCRIPTION
**Pull request by rullzer**
Related to https://github.com/nextcloud/server/pull/19978

Signed-off-by: Roeland Jago Douma <roeland@famdouma.nl>

### CODE REVIEW

**Comment by nickvergessen** [comment]
I'd like to not do this and instead fix storages to always return an owner. and if they dont have one, the mountpoint owner should be returned in my opinion:
https://github.com/nextcloud/groupfolders/pull/797

**Comment by nickvergessen** [comment]
> Conflicting files
lib/FilesHooks.php

:speak_no_evil: 

> I would still do this as then we would not break existing storage implementations that do not provide an owner yet.

Well, yes and no. Not breaking is good. On the other hand this is the only point where we know that our storages still return wrong info

**Comment by rullzer** [comment]
so... merge or close?

**Comment by juliushaertl** [comment]
> Well, yes and no. Not breaking is good. On the other hand this is the only point where we know that our storages still return wrong info.

Fine by me then, we still have some time to see during 19 beta/rc if that breaks somewhere and fix it then.

**Pull request closed without merging**
