### PR TITLE
feat(sidebar): Add frontend API that allows to register custom entries

### LINKED ISSUE #278: Improvements for Comments in Activity
As commented in https://github.com/nextcloud/android/pull/2690, there's some improvements we can do to how Comments show in the activity stream:

- The first line of a comment »Commented by you« is not really useful. It should simply say »You« instead (or the person's name)
- Similar for the icon: Instead of the generic comment icon, it should show the persons avatar

cc @nickvergessen

### PR DESCRIPTION
**Pull request by susnux**
* Resolves #278 
* Replaces #1396 

This adds a front end API that allows to register plugins on the Activity tab:
1. Register custom actions, this actions will be shown on top of the activity bar (e.g. a comments input)
2. Register custom stream elements, meaning custom entries in the activity stream (e.g. comments)
3. Register custom filter function for shown activities to filter out some

Why showing custom elements instead of the activity? Activities will be cleaned up while e.g. comments do not. So this allows e.g. comments to be shown within the activity sidebar tab.

### CODE REVIEW

**Comment by susnux** [comment]
The diff looks awful but in reality e.g. Activity.vue was just renamed to GenericActivity.vue and Activity.vue is now a wrapper...

**Comment by susnux** [comment]
A screen cast of how it looks when comments use it can be found here:
https://github.com/nextcloud/server/pull/41491

**Review by AndyScherzinger — APPROVED** [review]

**Review by artonge — APPROVED** [review]

**Pull request merged**
