### PR TITLE
Add filename in the preview docs

### PR DESCRIPTION
**Pull request by MorrisJobke**
cc @jancborchardt @tobiasKaminsky @nickvergessen 

For https://github.com/nextcloud/activity/pull/576/files#r630185430

### CODE REVIEW

**Comment by MorrisJobke** [comment]
I just wonder why this is added to the preview and not to the element itself 🤔

**Comment by MorrisJobke** [comment]
ref #576

**Comment by MorrisJobke** [comment]
@nickvergessen Tobias wondered yesterday if this should be seen as breaking change? There are JSON parsers out there that also break if new elements are added.

**Comment by nickvergessen** [comment]
> nickvergessen Tobias wondered yesterday if this should be seen as breaking change? There are JSON parsers out there that also break if new elements are added.

Adding additional items is per semver not a breaking change, so it should be fine. No need to duplicate the API unnecessarily.
Also any app could create a new object type and the clients should gracefully survive this.

> I just wonder why this is added to the preview and not to the element itself 🤔

Because the preview object is disconnected from the files object (not every file can has a preview) and it was just easier this way to inject the data on the level it is needed and available instead of starting to map values later on.

**Review by nickvergessen — APPROVED** [review]

**Comment by tobiasKaminsky** [comment]
> Adding additional items is per semver not a breaking change, so it should be fine. No need to duplicate the API unnecessarily.
> Also any app could create a new object type and the clients should gracefully survive this.

ok, did not knew this. I already checked with other clients to see that everything is working.

**Pull request merged**
